spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root.crj0seofnf1o.ap-northeast-2.rds.amazonaws.com:3306/haneum?useSSL=false&allowPublicKeyRetrieval=true&validationQuery="select 1"
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always


logging:
  level:
    haneum:
      troller: DEBUG
